### ISSUE TITLE
進入前端圈 52 天

### ISSUE THREAD

**Issue by maxhyun** [maxhyun/Note#1]
### modal-mark 相容性問題
`用 vue example`

```css
.modal-mask {
  position: fixed;
  z-index: 9998;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, .5);
  display: table;
  transition: opacity .3s ease;
}

.modal-wrapper {
  display: table-cell;
  vertical-align: middle;
}

.modal-container {
  width: 300px;
  margin: 0px auto;
  overflow: auto;
  padding: 20px 30px;
  background-color: #fff;
  border-radius: 2px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, .33);
  transition: all .3s ease;
  font-family: Helvetica, Arial, sans-serif;
}
```
**chrome** 正常 如果是 **IE11** or **FireFox**
`overflow` 會無法正常工作
**IE11** 解決辦法 
在 `modal-wrapper` 多加 `overflow: scroll;`
**FireFox** 不吃 `height%` 所以改用 `vh` 就可以兼容了

### vue 監聽 component 視窗大小

有個要隨使用者寬度的而生成的左右按鈕頁籤
頁籤數量如果超過視窗寬度就要顯示左右按鈕
需要監聽 `ul`寬度 跟 使用者螢幕寬度
`ul` 加上 `ref` 
methods 
```javascript
resize(){
let vm = this;
this.$nextTick(function(){
  if(!vm.$refs.divWidth){
   vm.offWidth = 0;
  }else{
   vm.offWidth = vm.$refs.divWidth.clientWidth;
  }
  if(!vm.$refs.ulWidth) {
    vm.listWidth = 0;
    } else{
       vm.listWidth = vm.$refs.ulWidth.clientWidth;
    }
})
```
再用 `watch` 監聽 `li` DOM 是否已經生成

### v-for 數字應用
遇到一個情境 可以新增多筆內文 
`input` 綁上 `v-model` 為一個 `array`
已知內文最多為20筆 在`data`中 給個 `dataNum=1`  如果新增內文 `dataNum++`
`v-for="item in dataNum"`
** v-for 用number時 itme從1開始**
在`v-model`中 `data[item-1]`
這樣就可以完整運行所需要的內文增加功能
